# Generated by Django 4.1.7 on 2023-03-02 09:18

from django.db import migrations, models
import hotels.hotel_model


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hotel_roomtype_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_supplier',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_customer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_supplier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to=hotels.hotel_model.PathAndRename('hotels_images')),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to=hotels.hotel_model.PathAndRename('rooms_images')),
        ),
    ]
