# Generated by Django 4.1.7 on 2023-03-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('arrival_airport', models.CharField(blank=True, max_length=50, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
