# Generated by Django 4.1.7 on 2023-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_booking_check_in_alter_booking_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
