# Generated by Django 4.1.7 on 2023-03-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_booking_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
