# Generated by Django 4.1.7 on 2023-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booking_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
